version: '3'
services:
  nginx:
   container_name: proxy
   image: nginx:1.14
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
  depends_on:
    - front_ent
  
  front_ent:
   container_name: front-ent
   build: ./front-ent
   volumes:
   - ./www:/www

  mysql:
   container_name: database
   build: ./back-end
   ports:
   - "3306:3306"
   restart: always

  app:
    restart: always
    build: ./back-end
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8082"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
