FROM node:8.10 as build
COPY ./ /app

WORKDIR /app
# RUN npm config set registry https://registry.npm.taobao.org && npm config get registry
# RUN npm install && npm run build
COPY ./dist/ /www
CMD ["tail", "-f", "/var/log/faillog"]
