FROM mysql:5.7
COPY ./ /app

WORKDIR /app
EXPOSE 3306

RUN sh /app/sql/init_data.sh /app/sql/init_data.sql
CMD service mysql restart && tail -f /var/log/mysql/error.log
# CMD ["sh", "/app/sql/init_data.sh", "/app/sql/init_data.sql"]
